name: E5-Rclone-Actions-Repo

on:
  push:
    branches:
      - main
  schedule:
    - cron: 30 1,13 * * *
  watch:
    types: started
jobs:
  run-it:
    runs-on: ubuntu-latest
    name: zip
    steps:

      - name: Checkout codes
        uses: actions/checkout@v2

      - name: Install rclone #安装rclone
        run: |
          latest_tag=$(curl -s https://api.github.com/repos/rclone/rclone/tags | grep -oP '"name": "\K(.*?)(?=")' | head -n 1)
          if [[ $latest_tag == v1.65* ]]; then
            deb_url="https://beta.rclone.org/branch/fix-onedrive-list/v1.66.0-beta.7551.0872f62ad.fix-onedrive-list/rclone-v1.66.0-beta.7551.0872f62ad.fix-onedrive-list-linux-amd64.deb"
          else
            deb_url="https://github.com/rclone/rclone/releases/download/$latest_tag/rclone-$latest_tag-linux-amd64.deb"
          fi
          wget "$deb_url" -O rclone.deb
          sudo dpkg -i rclone.deb
          rm rclone.deb

      - name: Unzip config #解压配置文件
        run: |
         mkdir -p ~/.config/rclone/
         unzip -P ${{ secrets.PASSWD }} rclone.zip -d ~/.config/rclone/
     
      - name: Run rclone #运行rclone
        run: |
          
          # 更改时区
          sudo cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          
          # 列出文件(此处不展示)
          echo "列出文件(此处不展示)"
          rclone lsd e5:/ > "lsd.log"
          rclone mkdir e5:/E5-Rclone-Actions-Repo/
          rclone move lsd.log e5:/E5-Rclone-Actions-Repo/
          rclone delete e5:/E5-Rclone-Actions-Repo/lsd.log
          rclone rmdir e5:/E5-Rclone-Actions-Repo/
      - name: Zip config #打包配置文件
        run: zip -P ${{ secrets.PASSWD }} rclone.zip -j ~/.config/rclone/rclone.conf

      - name: Commit config #提交配置文件
        run: |
         git config --global user.email "me@kmou424.moe"
         git config --global user.name "kmou424"
         git add .
         git commit -am "Auto update rclone config"
         git push
